add mobile gallery
nadiakhoptiuk/ice-cream-project pull request #23
Opened 2022-04-25 19:01 UTC by Ioanna-Istomina

2022-04-25 19:25 UTC, nadiakhoptiuk requested changes

2022-04-25 19:25 UTC, nadiakhoptiuk commented on src/sass/layout/_gallery.scss
> +    grid-template-columns: repeat(7, 40px);
можна поставити замість 40px calc(100% / 7), але тоді сітку розтягує, а зображення ні, може ще пограйся десь)) пошукай

2022-04-26 12:44 UTC, Ioanna-Istomina commented
Додала ще одну точку перелому в 480px

2022-04-26 13:46 UTC, nadiakhoptiuk requested changes

2022-04-26 13:46 UTC, nadiakhoptiuk commented on src/sass/layout/_gallery.scss
> +    width: 40px;
min-width: 40, max-width 60, width 100%

2022-04-26 13:46 UTC, nadiakhoptiuk commented on src/sass/layout/_gallery.scss
> +      width: 82px;
min-width: 82, max-width 123, width 100%.
попробуй.

2022-04-26 13:46 UTC, nadiakhoptiuk commented on src/sass/layout/_gallery.scss
> +      width: 52px;
тут 60пх. у всіх наступних медіа треба буде цим дівам дати max-width і значення, яке рівне буде їх значенням width.

тут буде:
width 60
max-width 60 

і тд

2022-04-26 13:46 UTC, nadiakhoptiuk commented on src/sass/layout/_gallery.scss
> +        width: 106px;
у всіх наступних медіа треба буде цим дівам дати max-width і значення, яке рівне буде їх значенням width.

тут 123пх

2022-04-26 19:22 UTC, nadiakhoptiuk approved these changes

2022-04-26 19:22 UTC, merged