Feature/header mob
nadiakhoptiuk/ice-cream-project pull request #24
Opened 2022-04-25 21:48 UTC by MaxKorolko

2022-04-26 08:06 UTC, nadiakhoptiuk requested changes

2022-04-26 08:06 UTC, nadiakhoptiuk commented on src/sass/layout/_header.scss
> +}
додати на іконку дісплей блок, бо там відступ в інлайна іде

2022-04-26 12:21 UTC, MaxKorolko commented on src/index.html
> +    <script src="./js/mobmenu.js"></script>
- [ ]

2022-04-26 12:39 UTC, MaxKorolko commented on src/js/mobmenu.js
> +  }
як залишиться час зроблю

2022-04-26 15:24 UTC, nadiakhoptiuk requested changes

2022-04-26 15:24 UTC, nadiakhoptiuk commented on src/sass/layout/_menu.scss
> +    stroke: currentColor;
поставив на кнопку, а не на іконку. працює хіба?

2022-04-26 15:24 UTC, nadiakhoptiuk commented on src/sass/layout/_menu.scss
> +    display: inline-block;
давай порадимось усі ввечері, мені здається що задумано так. і вирішимо всі)

2022-04-26 15:24 UTC, nadiakhoptiuk commented on src/sass/layout/_menu.scss
> +    margin-left: 9px;
марджин лівий обов'язково треба видалити, відступи від батьківського не ставляться

2022-04-26 15:24 UTC, nadiakhoptiuk commented on src/partials/header.html
> +        <button class="mob-menu__btn-order button-primary" type="button">
треба на цю кнопку повішати флекс і центрувати, іконка не по центру

2022-04-26 20:27 UTC, nadiakhoptiuk requested changes

2022-04-26 20:27 UTC, nadiakhoptiuk commented on src/sass/layout/_header.scss
> -
.page-header {
padding-top: 6px;
}
для таблетки і десктопа буде 37

2022-04-27 08:25 UTC, Lonardo17 approved these changes

2022-04-27 08:32 UTC, Lonardo17 approved these changes

2022-04-27 09:59 UTC, nadiakhoptiuk approved these changes

2022-04-27 09:59 UTC, merged