done-section
nadiakhoptiuk/ice-cream-project pull request #6
Opened 2022-04-23 13:25 UTC by Ilorety

2022-04-23 16:04 UTC, MaxKorolko requested changes

2022-04-23 16:04 UTC, MaxKorolko commented on src/partials/advantages.html
> +                <h2 class="Advantages___title">721</h2>
тут не `h2` , це `span` або `p` , на вибір

2022-04-23 16:04 UTC, MaxKorolko commented on src/partials/advantages.html
> +                <div class="Advantages___svg"></div>
гадаю для цієї картинки не потрібен окремий дів, її краще вставити через `:before`

2022-04-23 16:05 UTC, MaxKorolko commented on src/partials/about.html
> +            <h3 class="about__subtitle">
ну або краще `<b>`

2022-04-23 16:06 UTC, MaxKorolko commented on src/partials/about.html
> +            <h3 class="about__subtitle">
або ще краще `<b>`

2022-04-23 17:34 UTC, nadiakhoptiuk commented on src/partials/about.html
> +        <div class="about__img"></div>
тут дів не потрібен, буде просто img (picture)

2022-04-23 17:34 UTC, nadiakhoptiuk commented on src/partials/about.html
> +            <button class="about__button">Read more</button>
думаю, це не кнопка, а <a>, бо буде вести на іншу сторінку по логіці, клас можеш залишити свій

2022-04-23 17:34 UTC, nadiakhoptiuk commented on src/partials/advantages.html
> +<section class="Advantages___section">
зроби, будь ласка, всі назви класів з малої літери

2022-04-23 17:34 UTC, nadiakhoptiuk commented on src/partials/advantages.html
> +                <h2 class="Advantages___title">721</h2>
цифри краще у span однозначно

2022-04-23 17:52 UTC, nadiakhoptiuk commented
був закритий помилково, бо ще не внесено правки

2022-04-24 08:09 UTC, Ilorety commented on src/partials/about.html
> +            <button class="about__button">Read more</button>
готово)

2022-04-24 08:09 UTC, Ilorety commented on src/partials/advantages.html
> +<section class="Advantages___section">
готово)

2022-04-24 08:10 UTC, Ilorety commented on src/partials/about.html
> +        <div class="about__img"></div>
готово)

2022-04-24 08:11 UTC, Ilorety commented on src/partials/advantages.html
> +                <div class="Advantages___svg"></div>
готово)

2022-04-24 08:11 UTC, Ilorety commented on src/partials/advantages.html
> +                <h2 class="Advantages___title">721</h2>
готово)

2022-04-24 08:12 UTC, Ilorety commented on src/partials/about.html
> +            <h3 class="about__subtitle">
готово)

2022-04-24 08:14 UTC, nadiakhoptiuk approved these changes

2022-04-24 08:14 UTC, nadiakhoptiuk commented on src/partials/about.html
> +            </p>
тут напевно зробиш так як було, бо там марджина немає, що ж його на око вгадувати тепер? ( макет цікавий.. я прийму, а ти подумай, може зроби в один абзац через < br >, ще порадимось

2022-04-24 08:16 UTC, merged