Add footer html
nadiakhoptiuk/ice-cream-project pull request #8
Opened 2022-04-23 21:33 UTC by nadiakhoptiuk

2022-04-23 23:09 UTC, MaxKorolko requested changes

2022-04-23 23:09 UTC, MaxKorolko commented on src/partials/footer.html
> +    <span class="copyright">© 2019 - IceCream. All Rights Reserved. </span>
знак охорони авторських прав:  &copy;

2022-04-23 23:09 UTC, MaxKorolko commented on src/partials/footer.html
> +    <p class="footer__duplicate-title title">with passion</p>
`<div>` гадаю, ти залишила на потім?

2022-04-24 05:33 UTC, MaxKorolko approved these changes

2022-04-24 07:28 UTC, nadiakhoptiuk commented on src/partials/footer.html
> +    <span class="copyright">© 2019 - IceCream. All Rights Reserved. </span>
точно)) дякую

2022-04-24 07:37 UTC, MaxKorolko approved these changes

2022-04-24 07:48 UTC, merged